### ISSUE TITLE
Graph AAD Auth v1 exception (03653-18, 03653-20)

### ISSUE THREAD

**Issue by jakubcech** [OfficeDev/hands-on-labs#102]
Module Number: 03653-18, 03653-20
Module Title: Microsoft Graph People API, Insights from Microsoft Graph
Path of file:

I'm getting an auth exception when going through either _03653-18_ or _03653-20_, both of which are using the _Graph AAD Auth v1_ template. I wasn't able to reproduce this last week, but now I did get it on the first run in the lab environment. 

All I had to do was follow the scenario and NOT close the browser window or terminate the IIS process after the first F5 experience. Actually signing out and signing in resolves this, but this is not something the users do. We just tell them to go back to Visual Studio. 

Can someone try either of the labs and see if you get the same issue, or is there something obvious we do wrong in the controller actions? I tried returning an EmptyResult when I get an empty token back but that didn't seem to resolve the issue. This looks similar to the issue we had before the templates were updated.
### Stack

``` csharp
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Bearer access token is empty.",
    "innerError": {
      "request-id": "371be2a6-5cc7-415a-b91e-e189fbfb81a7",
      "date": "2016-03-29T06:15:37"
    }
  }
} 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: Microsoft.OData.Client.DataServiceClientException: {
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Bearer access token is empty.",
    "innerError": {
      "request-id": "371be2a6-5cc7-415a-b91e-e189fbfb81a7",
      "date": "2016-03-29T06:15:37"
    }
  }
}

Source Error: 

Line 19:         {
Line 20:             var service = await GetService();
Line 21:             return View(service.Me.People.ToList());
Line 22:         }
Line 23:         public async Task<string> GetToken()

Source File:  C:\Dev\PeopleGraphWeb\PeopleGraphWeb\Controllers\PeopleController.cs    Line:  21 

[DataServiceClientException: {
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Bearer access token is empty.",
    "innerError": {
      "request-id": "371be2a6-5cc7-415a-b91e-e189fbfb81a7",
      "date": "2016-03-29T06:15:37"
    }
  }
}]
   Microsoft.OData.Client.QueryResult.ExecuteQuery() +486
   Microsoft.OData.Client.DataServiceRequest.Execute(DataServiceContext context, QueryComponents queryComponents) +146

[DataServiceQueryException: An error occurred while processing this request.]
   Microsoft.OData.Client.DataServiceRequest.Execute(DataServiceContext context, QueryComponents queryComponents) +408
   Microsoft.OData.Client.DataServiceQuery`1.Execute() +176
   Microsoft.OData.Client.DataServiceQuery`1.GetEnumerator() +25
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +369
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   PeopleGraphWeb.Controllers.<Index>d__0.MoveNext() in C:\Dev\PeopleGraphWeb\PeopleGraphWeb\Controllers\PeopleController.cs:21
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   System.Threading.Tasks.TaskHelpersExtensions.ThrowIfFaulted(Task task) +42
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +73
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +37
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +68
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +69
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +230
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +68
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +42
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +124
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +32
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +26
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +40
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +24
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +29
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +23
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9742689
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

**Comment by jthake** [comment]
have you tried again with new tryoffice credentials? the accounts expire after 4 hours (passwords get reset automatically) and it might be that.

**Comment by jasonjoh** [comment]
Jeremy, I asked Jakub to add a check if the token is null before using it. Both of these labs use the same function to get the token, and it does no null/empty checking.

**Comment by jthake** [comment]
Does this just affect these two labs? Or all auth labs though?

Get Outlook for Mobile<https://aka.ms/cq8ksb>



On Tue, Mar 29, 2016 at 12:24 PM -0700, "Jason Johnston" <notifications@github.com<mailto:notifications@github.com>> wrote:


Jeremy, I asked Jakub to add a check if the token is null before using it. Both of these labs use the same function to get the token, and it does no null/empty checking.

-

**Comment by jasonjoh** [comment]
It could impact more than these, but it isn't template code. This is code added afterwards. For example, one lab says to add this code:

```
public async Task<string> GetToken()
{
    string userObjId = System.Security.Claims.ClaimsPrincipal.Current
        .FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;

    SessionTokenCache tokenCache = new SessionTokenCache(userObjId, HttpContext);

    string tenantId = System.Security.Claims.ClaimsPrincipal.Current
        .FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;

    string authority = string.Format(ConfigurationManager.AppSettings["ida:AADInstance"], tenantId, "");

    AuthHelper authHelper = new AuthHelper(authority, ConfigurationManager.AppSettings["ida:AppId"],
        ConfigurationManager.AppSettings["ida:AppSecret"], tokenCache);

    return await authHelper.GetUserAccessToken(Url.Action("Index", "Home", null, Request.Url.Scheme));
}

public async Task<Service.GraphService> GetService()
{
    string token = await GetToken();
    Service.GraphService service = new Service.GraphService(new Uri("https://graph.microsoft.com/beta/"));
    service.BuildingRequest += (sender, e) => e.Headers.Add("Authorization", "Bearer " + token);
    return service;
}
```

If `GetToken` returns null, then `GetService` adds a null string as the token, which would cause this exception from the OData client. An easy fix would be to add in `GetService` a check if `string.IsNullOrEmpty(token)` and redirect either to error page asking user to sign out and sign in again, or just redirect to the SignOut page.

**Comment by jakubcech** [comment]
Thanks, I updated the O3653-18 and O3653-20 projects to handle null tokens. I decided to make the checks in the actions themselves as opposed to GetService as I think that's more straightforward. But if you've got an elegant solution then I'll be happy to update the labs with that.

I also made some minor fixes in the People Graph lab. Will someone from the People team get a chance to do a quick run-through before tomorrow morning?
@MarianaStepp @edwardthMSFT @richardtaylorrt

**Comment by edwardthMSFT** [comment]
Hey,
	This issue actually impacts all labs that depend on the OAuth v1 or OAuth v2 template. The core problem is that the session cache is stored in IIS memory whereas the authentication status is stored in a cookie. When new code is deployed to IIS, IIS will invalidate the session cache but the cookie still lives in the browser. 
When presented with an empty token store, the OAuth v2 code just immediately returns an empty token (See AuthHelper->GetUserAccessToken). The OAuth v1 code appears to try to get a new token, but it does not work: (See AuthHelper->GetUserAccesToken: HttpContext.Current.Request.GetOwinContext().Authenticaiton.Challenge(new AuthenticaitonProperties() {RedirectUri=redirectUri}, OpenIdConnectAuthenticationDeafults.AuthenticationType);) 
One way to mitigate this would be to persist the session to the DB, which would fix the issue for the demo, but these tokens will expire eventually and the code should have a way of refreshing them. 
Another mitigation would be to alter the cookie provide to invalidate the login session if the token store expired.
The net effect is the same for all the quick-starts: If a user logins, then deploys new code, then reruns the code they will get back a null token.
The changes made to the people quickstart look to mitigate the issue effectively as well by trigger a logout. I’m not a huge fan of mixing the auth logic and app code, but given the time and the desire to keep the code small/simple I can’t think of a better way to handle the null tokens. 
A quick glance though a few other quick starts shows that they are not handling null tokens either and will exhibit the same crashing behavior if code is updated after a login.

Thanks,
Edward
