### ISSUE TITLE
O3653-7 Resource cannot be found when clicking View Pages link

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/hands-on-labs#104]
Module Number: O3653-7 exercise 2
Module Title: Microsoft Graph for OneNote Services
Path of file:
### Details of issue

When clicking the View Pages link in the Sections within Notebooks, the following error is displayed.  I verified that the notebook used does have pages.

![image](https://cloud.githubusercontent.com/assets/17051339/14122613/63f5f842-f5b1-11e5-8c45-0423bf917485.png)

**Comment by DianeD** [comment]
@lucas66 can you upload your updated solution?

**Comment by DianeD** [comment]
@lucas66 actually, on re-reading your issue,

**Comment by DianeD** [comment]
@vsharma77 to try to repro

**Comment by DianeD** [comment]
Trying to repro getting that bad path. Should be /notebooks/id/**sections**/id

**Comment by DianeD** [comment]
Still no repro. @AJMayMSFT tested it too.
