### ISSUE TITLE
Not an issue as such, but not many people are on builds 6741+ yet (does that need adding in the info?)

### ISSUE THREAD

**Issue by JerryMWeeks** [OfficeDev/hands-on-labs#113]
Module Number: O3652
Module Title: Home.js
Path of file: /StatementOfWork2Web/
### Details of issue Office version build 6741 and greater is not yet available for many people.

But when overridden the insert occurs anyway.
Line 182: 
 if (Office.context.requirements.isSetSupported("WordApi", "1.2")) {
Can the shortcoming of for example build 6001, be explained, or is it simply unstable?
Please feel free to delete this issue, but I am unsure how else to ask!

Fantastic functionality btw, really useful!

**Comment by mlafleur** [comment]
There are sometimes differences between what methods are actually available and what is reported by isSetSupported(). In general, isSetSupported() should only return true if the given set is available for production use on that host/platform.
