### ISSUE TITLE
Offce-docs O3653-2 Audience validation failed

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/hands-on-labs#91]
Module Number: O3653-2 Exercise 1
Module Title:  Connect to the Office 365 mail with the Microsoft Graph
Path of file:
### Details of issue

When first deploying the project and after creating and registering the app, I can sign in with my BuildChallenge user, but when I accept the permissions, I get this error:

IDX10214: Audience validation failed. Audiences: '8f7291b6-b275-4c47-b3e3-dc18580ad676'. Did not match: validationParameters.ValidAudience: ' 8f7291b6-b275-4c47-b3e3-dc18580ad676' or validationParameters.ValidAudiences: 'null'

**Comment by pretish** [comment]
Jeremy -  I don’t own this lab. Was this intentional?

**Comment by jthake** [comment]
changing to @Deepakbaghel99 . @VenkatAyyadevara-MSFT can you please take a look at this as this is urgent for tomorrow.

**Comment by VenkatAyyadevara-MSFT** [comment]
Hi Abdel,

Please take a look as you worked with Deepak on this issue as Jeremy needs this looked at before tomorrow.

Thanks
Venkat

**Comment by jthake** [comment]
This is really urgent guys so I’d appreciate you jumping on this one.

**Comment by VenkatAyyadevara-MSFT** [comment]
@abdelbahgat is going to take a look since @Deepakbaghel99 is OOF.

**Comment by abdelbahgat** [comment]
I cannot reproduce this issue.  I tried signing in with both Office365 (Enterprise) account and Outlook.com (consumer) account

**Comment by abdelbahgat** [comment]
@lucas66, would you please confirm this still repros? as I could not reproduce it.
